### PR TITLE
Hotfix/2.1.2

### PR DESCRIPTION
**Pull request by ohnoitsaustin**
this PR fixes "None" appearing for events before event details have been loaded from the server. It also adds a loading indicator.

### CODE REVIEW

**Comment by jhoerr** [comment]
I deployed the hotfix branch to the test site, but I don't see the loader. Can you confirm that it's working as expected here: http://igatracker-test.azurewebsites.net/ ? I tried browsing with Chrome's 'Slow 3G' network setting in dev tools.

**Comment by ohnoitsaustin** [comment]
Looks like they're mostly working - they appear next to the "Most Recent Event" and "Next Scheduled Event" headers. Screenshot from http://igatracker-test.azurewebsites.net/:

screen shot 2018-01-22 at 6 27 23 pm

I did refresh once or twice and they did not appear - inspecting the Network tab in chrome revealed that the loader.gif was not loaded until after the bill details ajax call. It should be cached in subsequent page views (I had cache disabled for testing), but the bill details will not be cached, so it should generally appear in time to be useful.

Let me know if you're not seeing it at all - maybe a browser issue? It's just a .gif as a css background.

**Comment by jhoerr** [comment]
Ahh ok, I see it now. Subtle! What do you think of spinners that gray out / disable the entire page until all the data is ready?

**Comment by ohnoitsaustin** [comment]
Just pushed an update - it displays a loader instead of the table until the details are loaded. This also avoids resizing all of the rows when the details are loaded, which I found disorienting.

Thoughts? I can add this to the All legislation view as well.

**Comment by ohnoitsaustin** [comment]
It should appear like this while loading 
screen shot 2018-01-23 at 11 06 46 am

**Comment by jhoerr** [comment]
That loading gif is my new favorite thing in the entire world.

**Comment by jhoerr** [comment]
And yeah, let's add it to the All Legislation view as well. I love this!

**Comment by jhoerr** [comment]
I'm deploying this to the test server for review.

**Comment by ohnoitsaustin** [comment]
Glad ya'll like it! It was fun to play with in After Effects. 

I've closed this locally and pushed up to `develop`, okay if I push up `master`?

**Comment by jhoerr** [comment]
Yep, it looks good on the test server. 

FYI, you can use git flow to push releases and hotfixes with the _-p_ flag:  `git flow hotfix finish -p 2.1.2`

**Pull request merged**
